;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        backward-sexp
        c-electric-delete-forward
        c-indent-line-or-region
        forward-sentence
        ))

(setq mc/cmds-to-run-once
      '(
        ))
